import { MigrationInterface, QueryRunner } from "typeorm";

export class AddXaPhuongIdCumKhuCnIdToBaoCao1760229192478 implements MigrationInterface {
    name = 'AddXaPhuongIdCumKhuCnIdToBaoCao1760229192478'

    public async up(queryRunner: QueryRunner): Promise<void> {
        console.log('⚠️ Skipping legacy AddXaPhuongIdCumKhuCnIdToBaoCao migration');
        return;
        await queryRunner.query(`ALTER TABLE \`oa_follow_events\` DROP FOREIGN KEY \`FK_bc8cf00c4644e654c84124b3fe2\``);
        await queryRunner.query(`ALTER TABLE \`su_kien\` DROP FOREIGN KEY \`FK_su_kien_loai_su_kien\``);
        await queryRunner.query(`ALTER TABLE \`su_kien\` DROP FOREIGN KEY \`FK_su_kien_nguoi_tao\``);
        await queryRunner.query(`ALTER TABLE \`nguoi_nhan_su_kien\` DROP FOREIGN KEY \`FK_nguoi_nhan_su_kien_nguoi_nhan\``);
        await queryRunner.query(`ALTER TABLE \`nguoi_nhan_su_kien\` DROP FOREIGN KEY \`FK_nguoi_nhan_su_kien_su_kien\``);
        await queryRunner.query(`ALTER TABLE \`organization\` DROP FOREIGN KEY \`FK_organization_cumKhuCongNghiep\``);
        await queryRunner.query(`ALTER TABLE \`staff\` DROP FOREIGN KEY \`FK_staff_organization\``);
        await queryRunner.query(`ALTER TABLE \`user_thong_bao\` DROP FOREIGN KEY \`FK_user_thong_bao_thong_bao\``);
        await queryRunner.query(`ALTER TABLE \`user_thong_bao\` DROP FOREIGN KEY \`FK_user_thong_bao_user\``);
        await queryRunner.query(`ALTER TABLE \`thong_bao\` DROP FOREIGN KEY \`FK_thong_bao_nguoi_gui\``);
        await queryRunner.query(`ALTER TABLE \`UserToken\` DROP FOREIGN KEY \`FK_usertoken_user\``);
        await queryRunner.query(`ALTER TABLE \`zalo_users\` DROP FOREIGN KEY \`FK_zalo_users_userId\``);
        await queryRunner.query(`DROP INDEX \`IDX_bao_cao_doan_so_nguoi_phe_duyet\` ON \`bao_cao_doan_so_theo_ky\``);
        await queryRunner.query(`DROP INDEX \`IDX_oa_follow_events_oa_user_id\` ON \`oa_follow_events\``);
        await queryRunner.query(`DROP INDEX \`IDX_oa_follow_events_processed\` ON \`oa_follow_events\``);
        await queryRunner.query(`DROP INDEX \`IDX_oa_follow_events_type\` ON \`oa_follow_events\``);
        await queryRunner.query(`DROP INDEX \`IDX_oa_follow_events_zalo_account_id\` ON \`oa_follow_events\``);
        await queryRunner.query(`DROP INDEX \`UK_nguoi_nhan_su_kien\` ON \`nguoi_nhan_su_kien\``);
        await queryRunner.query(`DROP INDEX \`IDX_organization_cumKhuCnId\` ON \`organization\``);
        await queryRunner.query(`DROP INDEX \`fieldKey\` ON \`OrganizationFieldSchema\``);
        await queryRunner.query(`DROP INDEX \`IDX_organization_field_schema_fieldKey\` ON \`OrganizationFieldSchema\``);
        await queryRunner.query(`DROP INDEX \`IDX_organization_field_schema_sort_active\` ON \`OrganizationFieldSchema\``);
        await queryRunner.query(`DROP INDEX \`IDX_thoi_gian_cap_nhat_doan_so_isActive\` ON \`ThoiGianCapNhatDoanSo\``);
        await queryRunner.query(`DROP INDEX \`IDX_thoi_gian_cap_nhat_doan_so_next_notification\` ON \`ThoiGianCapNhatDoanSo\``);
        await queryRunner.query(`DROP INDEX \`IDX_thoi_gian_cap_nhat_doan_so_time_range\` ON \`ThoiGianCapNhatDoanSo\``);
        await queryRunner.query(`DROP INDEX \`idx_active\` ON \`zalo_oa_tokens\``);
        await queryRunner.query(`DROP INDEX \`idx_expires_at\` ON \`zalo_oa_tokens\``);
        await queryRunner.query(`DROP INDEX \`idx_oa_id\` ON \`zalo_oa_tokens\``);
        await queryRunner.query(`DROP INDEX \`IDX_zalo_sessions_expires_at\` ON \`zalo_sessions\``);
        await queryRunner.query(`DROP INDEX \`IDX_zalo_sessions_status\` ON \`zalo_sessions\``);
        await queryRunner.query(`DROP INDEX \`IDX_zalo_sessions_user_id\` ON \`zalo_sessions\``);
        await queryRunner.query(`DROP INDEX \`UQ_f6684d46d6ee3570e8dceef21c0\` ON \`zalo_sessions\``);
        await queryRunner.query(`DROP INDEX \`IDX_zalo_accounts_app_user_id\` ON \`zalo_accounts\``);
        await queryRunner.query(`DROP INDEX \`IDX_zalo_accounts_following\` ON \`zalo_accounts\``);
        await queryRunner.query(`DROP INDEX \`IDX_zalo_accounts_oa_user_id\` ON \`zalo_accounts\``);
        await queryRunner.query(`DROP INDEX \`IDX_zalo_accounts_user_id\` ON \`zalo_accounts\``);
        await queryRunner.query(`DROP INDEX \`IDX_zalo_accounts_zalo_mini_app_id\` ON \`zalo_accounts\``);
        await queryRunner.query(`DROP INDEX \`UK_zalo_users_zaloId\` ON \`zalo_users\``);
        await queryRunner.query(`CREATE TABLE \`accounts\` (\`id\` int NOT NULL AUTO_INCREMENT, \`status\` varchar(255) NULL, \`descriptions\` varchar(255) NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`zalo_tokens\` (\`id\` int NOT NULL AUTO_INCREMENT, \`token_type\` varchar(50) NOT NULL, \`token_value\` text NOT NULL, \`expires_at\` bigint NULL, \`app_id\` varchar(100) NOT NULL, \`is_active\` tinyint NOT NULL DEFAULT '1', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`oa_follow_events\` DROP COLUMN \`error_message\``);
        await queryRunner.query(`ALTER TABLE \`oa_follow_events\` DROP COLUMN \`event_data\``);
        await queryRunner.query(`ALTER TABLE \`oa_follow_events\` DROP COLUMN \`event_type\``);
        await queryRunner.query(`ALTER TABLE \`oa_follow_events\` DROP COLUMN \`is_processed\``);
        await queryRunner.query(`ALTER TABLE \`oa_follow_events\` DROP COLUMN \`processed_at\``);
        await queryRunner.query(`ALTER TABLE \`oa_follow_events\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`oa_follow_events\` DROP COLUMN \`zalo_account_id\``);
        await queryRunner.query(`ALTER TABLE \`organization\` DROP COLUMN \`namThanhLap_backup\``);
        await queryRunner.query(`ALTER TABLE \`staff\` DROP COLUMN \`bankAccount\``);
        await queryRunner.query(`ALTER TABLE \`staff\` DROP COLUMN \`bankName\``);
        await queryRunner.query(`ALTER TABLE \`staff\` DROP COLUMN \`contractType\``);
        await queryRunner.query(`ALTER TABLE \`staff\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`staff\` DROP COLUMN \`healthInsuranceNumber\``);
        await queryRunner.query(`ALTER TABLE \`staff\` DROP COLUMN \`isActive\``);
        await queryRunner.query(`ALTER TABLE \`staff\` DROP COLUMN \`isDelete\``);
        await queryRunner.query(`ALTER TABLE \`staff\` DROP COLUMN \`salaryLevel\``);
        await queryRunner.query(`ALTER TABLE \`staff\` DROP COLUMN \`socialInsuranceNumber\``);
        await queryRunner.query(`ALTER TABLE \`staff\` DROP COLUMN \`taxCode\``);
        await queryRunner.query(`ALTER TABLE \`staff\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`staff\` DROP COLUMN \`workStartDate\``);
        await queryRunner.query(`ALTER TABLE \`zalo_sessions\` DROP COLUMN \`code_challenge\``);
        await queryRunner.query(`ALTER TABLE \`zalo_sessions\` DROP COLUMN \`code_verifier\``);
        await queryRunner.query(`ALTER TABLE \`zalo_sessions\` DROP COLUMN \`oauth_code\``);
        await queryRunner.query(`ALTER TABLE \`zalo_sessions\` DROP COLUMN \`redirect_uri\``);
        await queryRunner.query(`ALTER TABLE \`zalo_sessions\` DROP COLUMN \`session_key\``);
        await queryRunner.query(`ALTER TABLE \`zalo_sessions\` DROP COLUMN \`status\``);
        await queryRunner.query(`ALTER TABLE \`zalo_sessions\` DROP COLUMN \`user_id\``);
        await queryRunner.query(`ALTER TABLE \`bao_cao_doan_so_theo_ky\` ADD \`xaPhuongId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`bao_cao_doan_so_theo_ky\` ADD \`cumKhuCnId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`oa_follow_events\` ADD \`event_name\` varchar(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`oa_follow_events\` ADD \`timestamp\` datetime NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`oa_follow_events\` ADD \`source\` varchar(50) NULL`);
        await queryRunner.query(`ALTER TABLE \`oa_follow_events\` ADD \`raw_data\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`staff\` ADD \`degree\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`staff\` ADD \`title\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`staff\` ADD \`image\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`staff\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`staff\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`zalo_sessions\` ADD \`zalo_account_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`zalo_sessions\` ADD \`is_active\` tinyint NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`id\` int NOT NULL PRIMARY KEY AUTO_INCREMENT`);
        // Fix NULL values first, then change to NOT NULL
        await queryRunner.query(`UPDATE \`user\` SET \`forgetPassCode\` = '' WHERE \`forgetPassCode\` IS NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`forgetPassCode\` \`forgetPassCode\` varchar(255) NOT NULL`);
        // Fix NULL values for fullName
        await queryRunner.query(`UPDATE \`user\` SET \`fullName\` = '' WHERE \`fullName\` IS NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`fullName\` \`fullName\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`phoneNumber\``);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`phoneNumber\` varchar(255) NOT NULL`);
        // Fix NULL values for email  
        await queryRunner.query(`UPDATE \`user\` SET \`email\` = '' WHERE \`email\` IS NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`email\` \`email\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`avatar\``);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`avatar\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`description\``);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`description\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`cumKhuCnId\` \`cumKhuCnId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`xaPhuongId\` \`xaPhuongId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`bao_cao_doan_so_theo_ky\` CHANGE \`organizationId\` \`organizationId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`bao_cao_doan_so_theo_ky\` DROP COLUMN \`trangThaiPheDuyet\``);
        await queryRunner.query(`ALTER TABLE \`bao_cao_doan_so_theo_ky\` ADD \`trangThaiPheDuyet\` enum ('cho_phe_duyet', 'da_phe_duyet', 'tu_choi') NOT NULL DEFAULT 'cho_phe_duyet'`);
        await queryRunner.query(`ALTER TABLE \`bao_cao_doan_so_theo_ky\` DROP COLUMN \`nguoiPheDuyetId\``);
        await queryRunner.query(`ALTER TABLE \`bao_cao_doan_so_theo_ky\` ADD \`nguoiPheDuyetId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`bao_cao_doan_so_theo_ky\` CHANGE \`ngayPheDuyet\` \`ngayPheDuyet\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`loai_su_kien\` CHANGE \`ten\` \`ten\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`loai_su_kien\` CHANGE \`mo_ta\` \`mo_ta\` varchar(500) NULL`);
        await queryRunner.query(`ALTER TABLE \`loai_su_kien\` CHANGE \`trang_thai\` \`trang_thai\` tinyint NOT NULL DEFAULT 1`);
        await queryRunner.query(`ALTER TABLE \`loai_su_kien\` CHANGE \`created_at\` \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`loai_su_kien\` CHANGE \`updated_at\` \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`oa_follow_events\` CHANGE \`id\` \`id\` bigint NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`oa_follow_events\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`oa_follow_events\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`oa_follow_events\` ADD \`id\` int NOT NULL PRIMARY KEY AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`oa_follow_events\` CHANGE \`zalo_oa_user_id\` \`zalo_oa_user_id\` varchar(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`oa_follow_events\` CHANGE \`created_at\` \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`su_kien\` CHANGE \`ten_su_kien\` \`ten_su_kien\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`su_kien\` CHANGE \`thoi_gian_bat_dau\` \`thoi_gian_bat_dau\` datetime NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`su_kien\` CHANGE \`thoi_gian_ket_thuc\` \`thoi_gian_ket_thuc\` datetime NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`su_kien\` DROP COLUMN \`nguoi_tao\``);
        await queryRunner.query(`ALTER TABLE \`su_kien\` ADD \`nguoi_tao\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`su_kien\` CHANGE \`noi_dung_su_kien\` \`noi_dung_su_kien\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`su_kien\` CHANGE \`dia_diem\` \`dia_diem\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`su_kien\` CHANGE \`trang_thai\` \`trang_thai\` varchar(50) NOT NULL DEFAULT 'Đang chuẩn bị'`);
        await queryRunner.query(`ALTER TABLE \`su_kien\` CHANGE \`doi_tuong\` \`doi_tuong\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`su_kien\` CHANGE \`loai_su_kien_id\` \`loai_su_kien_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`su_kien\` CHANGE \`so_luong_tham_gia_du_kien\` \`so_luong_tham_gia_du_kien\` int NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`su_kien\` CHANGE \`file_dinh_kem\` \`file_dinh_kem\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`su_kien\` CHANGE \`ghi_chu\` \`ghi_chu\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`su_kien\` CHANGE \`created_at\` \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`su_kien\` CHANGE \`updated_at\` \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`nguoi_nhan_su_kien\` DROP COLUMN \`nguoi_nhan_id\``);
        await queryRunner.query(`ALTER TABLE \`nguoi_nhan_su_kien\` ADD \`nguoi_nhan_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`nguoi_nhan_su_kien\` CHANGE \`su_kien_id\` \`su_kien_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`nguoi_nhan_su_kien\` CHANGE \`trang_thai_xem\` \`trang_thai_xem\` varchar(20) NOT NULL DEFAULT 'Chưa xem'`);
        await queryRunner.query(`ALTER TABLE \`nguoi_nhan_su_kien\` CHANGE \`thoi_gian_gui\` \`thoi_gian_gui\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`nguoi_nhan_su_kien\` CHANGE \`thoi_gian_xem\` \`thoi_gian_xem\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`nguoi_nhan_su_kien\` CHANGE \`loai_thong_bao\` \`loai_thong_bao\` varchar(50) NOT NULL DEFAULT 'Thông báo sự kiện'`);
        await queryRunner.query(`ALTER TABLE \`nguoi_nhan_su_kien\` CHANGE \`ghi_chu\` \`ghi_chu\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`nguoi_nhan_su_kien\` CHANGE \`created_at\` \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`nguoi_nhan_su_kien\` CHANGE \`updated_at\` \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`organization\` CHANGE \`name\` \`name\` varchar(255) NOT NULL COMMENT 'Tên tổ chức'`);
        await queryRunner.query(`ALTER TABLE \`organization\` CHANGE \`slCongNhanVienChucLdNam\` \`slCongNhanVienChucLdNam\` int NOT NULL COMMENT 'Số lượng công nhân viên chức lao động nam' DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`organization\` CHANGE \`slCongNhanVienChucLdNu\` \`slCongNhanVienChucLdNu\` int NOT NULL COMMENT 'Số lượng công nhân viên chức lao động nữ' DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`organization\` CHANGE \`slCongDoanNam\` \`slCongDoanNam\` int NOT NULL COMMENT 'Số lượng công đoàn nam' DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`organization\` CHANGE \`slCongDoanNu\` \`slCongDoanNu\` int NOT NULL COMMENT 'Số lượng công đoàn nữ' DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`organization\` CHANGE \`createdAt\` \`createdAt\` datetime(6) NOT NULL COMMENT 'Ngày tạo' DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`organization\` CHANGE \`updatedAt\` \`updatedAt\` datetime(6) NOT NULL COMMENT 'Ngày cập nhật' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`role\` CHANGE \`isActive\` \`isActive\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`role\` DROP COLUMN \`permissions\``);
        await queryRunner.query(`ALTER TABLE \`role\` ADD \`permissions\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`role\` DROP COLUMN \`description\``);
        await queryRunner.query(`ALTER TABLE \`role\` ADD \`description\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`user_thong_bao\` DROP COLUMN \`userId\``);
        await queryRunner.query(`ALTER TABLE \`user_thong_bao\` ADD \`userId\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`user_thong_bao\` DROP COLUMN \`trang_thai\``);
        await queryRunner.query(`ALTER TABLE \`user_thong_bao\` ADD \`trang_thai\` enum ('chua_doc', 'da_doc', 'da_xoa') NOT NULL DEFAULT 'chua_doc'`);
        await queryRunner.query(`ALTER TABLE \`thong_bao\` DROP COLUMN \`nguoi_gui\``);
        await queryRunner.query(`ALTER TABLE \`thong_bao\` ADD \`nguoi_gui\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`UserToken\` DROP COLUMN \`token\``);
        await queryRunner.query(`ALTER TABLE \`UserToken\` ADD \`token\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`UserToken\` DROP COLUMN \`deviceInfo\``);
        await queryRunner.query(`ALTER TABLE \`UserToken\` ADD \`deviceInfo\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`UserToken\` CHANGE \`isActive\` \`isActive\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`zalo_oa_tokens\` CHANGE \`oa_id\` \`oa_id\` varchar(255) NOT NULL COMMENT 'Zalo OA ID'`);
        await queryRunner.query(`ALTER TABLE \`zalo_oa_tokens\` CHANGE \`access_token\` \`access_token\` text NOT NULL COMMENT 'Access token của Zalo OA'`);
        await queryRunner.query(`ALTER TABLE \`zalo_oa_tokens\` CHANGE \`expires_in\` \`expires_in\` int NOT NULL COMMENT 'Thời gian hết hạn token (seconds)'`);
        await queryRunner.query(`ALTER TABLE \`zalo_oa_tokens\` CHANGE \`expires_at\` \`expires_at\` datetime NOT NULL COMMENT 'Thời điểm hết hạn token'`);
        await queryRunner.query(`ALTER TABLE \`zalo_oa_tokens\` CHANGE \`token_type\` \`token_type\` varchar(50) NOT NULL COMMENT 'Loại token' DEFAULT 'Bearer'`);
        await queryRunner.query(`ALTER TABLE \`zalo_oa_tokens\` CHANGE \`is_active\` \`is_active\` tinyint NOT NULL COMMENT '1: Active, 0: Inactive' DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`zalo_oa_tokens\` CHANGE \`created_at\` \`created_at\` datetime(6) NOT NULL COMMENT 'Thời gian tạo' DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`zalo_oa_tokens\` CHANGE \`updated_at\` \`updated_at\` datetime(6) NOT NULL COMMENT 'Thời gian cập nhật' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`zalo_sessions\` CHANGE \`id\` \`id\` bigint NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`zalo_sessions\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`zalo_sessions\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`zalo_sessions\` ADD \`id\` int NOT NULL PRIMARY KEY AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`zalo_sessions\` DROP COLUMN \`access_token\``);
        await queryRunner.query(`ALTER TABLE \`zalo_sessions\` ADD \`access_token\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`zalo_sessions\` DROP COLUMN \`refresh_token\``);
        await queryRunner.query(`ALTER TABLE \`zalo_sessions\` ADD \`refresh_token\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`zalo_sessions\` CHANGE \`expires_at\` \`expires_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`zalo_sessions\` CHANGE \`created_at\` \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`zalo_sessions\` CHANGE \`updated_at\` \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`zalo_accounts\` CHANGE \`id\` \`id\` bigint NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`zalo_accounts\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`zalo_accounts\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`zalo_accounts\` ADD \`id\` int NOT NULL PRIMARY KEY AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`zalo_accounts\` DROP COLUMN \`user_id\``);
        await queryRunner.query(`ALTER TABLE \`zalo_accounts\` ADD \`user_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`zalo_accounts\` DROP COLUMN \`avatar\``);
        await queryRunner.query(`ALTER TABLE \`zalo_accounts\` ADD \`avatar\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`zalo_accounts\` CHANGE \`is_following_oa\` \`is_following_oa\` tinyint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`zalo_accounts\` CHANGE \`last_follow_at\` \`last_follow_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`zalo_accounts\` CHANGE \`last_unfollow_at\` \`last_unfollow_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`zalo_accounts\` CHANGE \`last_active_at\` \`last_active_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`zalo_accounts\` DROP COLUMN \`phone\``);
        await queryRunner.query(`ALTER TABLE \`zalo_accounts\` ADD \`phone\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`zalo_accounts\` CHANGE \`additional_info\` \`additional_info\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`zalo_accounts\` CHANGE \`last_login_at\` \`last_login_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`zalo_accounts\` CHANGE \`is_active\` \`is_active\` tinyint NOT NULL DEFAULT 1`);
        await queryRunner.query(`ALTER TABLE \`zalo_accounts\` CHANGE \`created_at\` \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`zalo_accounts\` CHANGE \`updated_at\` \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`zalo_users\` CHANGE \`zaloId\` \`zaloId\` varchar(255) NOT NULL COMMENT 'Zalo User ID'`);
        await queryRunner.query(`ALTER TABLE \`zalo_users\` ADD UNIQUE INDEX \`IDX_fa9be7c269ee7b665ca0c13a1c\` (\`zaloId\`)`);
        await queryRunner.query(`ALTER TABLE \`zalo_users\` CHANGE \`name\` \`name\` varchar(255) NOT NULL COMMENT 'Tên người dùng Zalo'`);
        await queryRunner.query(`ALTER TABLE \`zalo_users\` DROP COLUMN \`phone\``);
        await queryRunner.query(`ALTER TABLE \`zalo_users\` ADD \`phone\` varchar(255) NULL COMMENT 'Số điện thoại'`);
        await queryRunner.query(`ALTER TABLE \`zalo_users\` CHANGE \`avatar\` \`avatar\` text NULL COMMENT 'Avatar URL'`);
        await queryRunner.query(`ALTER TABLE \`zalo_users\` DROP COLUMN \`userId\``);
        await queryRunner.query(`ALTER TABLE \`zalo_users\` ADD \`userId\` int NULL COMMENT 'Liên kết với user hệ thống'`);
        await queryRunner.query(`ALTER TABLE \`zalo_users\` ADD UNIQUE INDEX \`IDX_b613a83f8b87de0702c28d313a\` (\`userId\`)`);
        await queryRunner.query(`ALTER TABLE \`zalo_users\` CHANGE \`isActive\` \`isActive\` tinyint NOT NULL COMMENT 'Trạng thái hoạt động' DEFAULT 1`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`forgetPassCode\` \`forgetPassCode\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`fullName\` \`fullName\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`email\` \`email\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`cumKhuCnId\` \`cumKhuCnId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`xaPhuongId\` \`xaPhuongId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`bao_cao_doan_so_theo_ky\` CHANGE \`ngayPheDuyet\` \`ngayPheDuyet\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`oa_follow_events\` CHANGE \`zalo_oa_user_id\` \`zalo_oa_user_id\` varchar(50) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`oa_follow_events\` CHANGE \`created_at\` \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`loai_su_kien\` CHANGE \`ten\` \`ten\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`loai_su_kien\` CHANGE \`mo_ta\` \`mo_ta\` varchar(500) NULL`);
        await queryRunner.query(`ALTER TABLE \`loai_su_kien\` CHANGE \`trang_thai\` \`trang_thai\` tinyint NOT NULL DEFAULT 1`);
        await queryRunner.query(`ALTER TABLE \`loai_su_kien\` CHANGE \`created_at\` \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`loai_su_kien\` CHANGE \`updated_at\` \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`su_kien\` CHANGE \`ten_su_kien\` \`ten_su_kien\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`su_kien\` CHANGE \`thoi_gian_bat_dau\` \`thoi_gian_bat_dau\` datetime NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`su_kien\` CHANGE \`thoi_gian_ket_thuc\` \`thoi_gian_ket_thuc\` datetime NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`su_kien\` CHANGE \`noi_dung_su_kien\` \`noi_dung_su_kien\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`su_kien\` CHANGE \`dia_diem\` \`dia_diem\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`su_kien\` CHANGE \`trang_thai\` \`trang_thai\` varchar(50) NOT NULL DEFAULT 'Đang chuẩn bị'`);
        await queryRunner.query(`ALTER TABLE \`su_kien\` CHANGE \`doi_tuong\` \`doi_tuong\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`su_kien\` CHANGE \`loai_su_kien_id\` \`loai_su_kien_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`su_kien\` CHANGE \`so_luong_tham_gia_du_kien\` \`so_luong_tham_gia_du_kien\` int NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`su_kien\` CHANGE \`file_dinh_kem\` \`file_dinh_kem\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`su_kien\` CHANGE \`ghi_chu\` \`ghi_chu\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`su_kien\` CHANGE \`created_at\` \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`su_kien\` CHANGE \`updated_at\` \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`nguoi_nhan_su_kien\` CHANGE \`su_kien_id\` \`su_kien_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`nguoi_nhan_su_kien\` CHANGE \`trang_thai_xem\` \`trang_thai_xem\` varchar(20) NOT NULL DEFAULT 'Chưa xem'`);
        await queryRunner.query(`ALTER TABLE \`nguoi_nhan_su_kien\` CHANGE \`thoi_gian_gui\` \`thoi_gian_gui\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`nguoi_nhan_su_kien\` CHANGE \`thoi_gian_xem\` \`thoi_gian_xem\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`nguoi_nhan_su_kien\` CHANGE \`loai_thong_bao\` \`loai_thong_bao\` varchar(50) NOT NULL DEFAULT 'Thông báo sự kiện'`);
        await queryRunner.query(`ALTER TABLE \`nguoi_nhan_su_kien\` CHANGE \`ghi_chu\` \`ghi_chu\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`nguoi_nhan_su_kien\` CHANGE \`created_at\` \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`nguoi_nhan_su_kien\` CHANGE \`updated_at\` \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`organization\` CHANGE \`name\` \`name\` varchar(255) NOT NULL COMMENT 'Tên tổ chức'`);
        await queryRunner.query(`ALTER TABLE \`organization\` CHANGE \`slCongNhanVienChucLdNam\` \`slCongNhanVienChucLdNam\` int NOT NULL COMMENT 'Số lượng công nhân viên chức lao động nam' DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`organization\` CHANGE \`slCongNhanVienChucLdNu\` \`slCongNhanVienChucLdNu\` int NOT NULL COMMENT 'Số lượng công nhân viên chức lao động nữ' DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`organization\` CHANGE \`slCongDoanNam\` \`slCongDoanNam\` int NOT NULL COMMENT 'Số lượng công đoàn nam' DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`organization\` CHANGE \`slCongDoanNu\` \`slCongDoanNu\` int NOT NULL COMMENT 'Số lượng công đoàn nữ' DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`organization\` CHANGE \`createdAt\` \`createdAt\` datetime(6) NOT NULL COMMENT 'Ngày tạo' DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`organization\` CHANGE \`updatedAt\` \`updatedAt\` datetime(6) NOT NULL COMMENT 'Ngày cập nhật' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`role\` CHANGE \`isActive\` \`isActive\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`UserToken\` CHANGE \`isActive\` \`isActive\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`zalo_sessions\` CHANGE \`expires_at\` \`expires_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`zalo_sessions\` CHANGE \`created_at\` \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`zalo_sessions\` CHANGE \`updated_at\` \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`zalo_accounts\` CHANGE \`is_following_oa\` \`is_following_oa\` tinyint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`zalo_accounts\` CHANGE \`last_follow_at\` \`last_follow_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`zalo_accounts\` CHANGE \`last_unfollow_at\` \`last_unfollow_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`zalo_accounts\` CHANGE \`last_active_at\` \`last_active_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`zalo_accounts\` CHANGE \`additional_info\` \`additional_info\` json NULL`);
        await queryRunner.query(`ALTER TABLE \`zalo_accounts\` CHANGE \`last_login_at\` \`last_login_at\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`zalo_accounts\` CHANGE \`is_active\` \`is_active\` tinyint NOT NULL DEFAULT 1`);
        await queryRunner.query(`ALTER TABLE \`zalo_accounts\` CHANGE \`created_at\` \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`zalo_accounts\` CHANGE \`updated_at\` \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`zalo_oa_tokens\` CHANGE \`oa_id\` \`oa_id\` varchar(255) NOT NULL COMMENT 'Zalo OA ID'`);
        await queryRunner.query(`ALTER TABLE \`zalo_oa_tokens\` CHANGE \`access_token\` \`access_token\` text NOT NULL COMMENT 'Access token của Zalo OA'`);
        await queryRunner.query(`ALTER TABLE \`zalo_oa_tokens\` CHANGE \`expires_in\` \`expires_in\` int NOT NULL COMMENT 'Thời gian hết hạn token (seconds)'`);
        await queryRunner.query(`ALTER TABLE \`zalo_oa_tokens\` CHANGE \`expires_at\` \`expires_at\` datetime NOT NULL COMMENT 'Thời điểm hết hạn token'`);
        await queryRunner.query(`ALTER TABLE \`zalo_oa_tokens\` CHANGE \`token_type\` \`token_type\` varchar(50) NOT NULL COMMENT 'Loại token' DEFAULT 'Bearer'`);
        await queryRunner.query(`ALTER TABLE \`zalo_oa_tokens\` CHANGE \`is_active\` \`is_active\` tinyint NOT NULL COMMENT '1: Active, 0: Inactive' DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`zalo_oa_tokens\` CHANGE \`created_at\` \`created_at\` datetime(6) NOT NULL COMMENT 'Thời gian tạo' DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`zalo_oa_tokens\` CHANGE \`updated_at\` \`updated_at\` datetime(6) NOT NULL COMMENT 'Thời gian cập nhật' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`zalo_users\` CHANGE \`zaloId\` \`zaloId\` varchar(255) NOT NULL COMMENT 'Zalo User ID'`);
        await queryRunner.query(`ALTER TABLE \`zalo_users\` ADD UNIQUE INDEX \`IDX_fa9be7c269ee7b665ca0c13a1c\` (\`zaloId\`)`);
        await queryRunner.query(`ALTER TABLE \`zalo_users\` CHANGE \`name\` \`name\` varchar(255) NOT NULL COMMENT 'Tên người dùng Zalo'`);
        await queryRunner.query(`ALTER TABLE \`zalo_users\` CHANGE \`avatar\` \`avatar\` text NULL COMMENT 'Avatar URL'`);
        await queryRunner.query(`ALTER TABLE \`zalo_users\` CHANGE \`isActive\` \`isActive\` tinyint NOT NULL COMMENT 'Trạng thái hoạt động' DEFAULT 1`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_9b05ed01c36388ac6f45dee0a0\` ON \`OrganizationFieldSchema\` (\`fieldKey\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`UK_user_thong_bao\` ON \`user_thong_bao\` (\`userId\`, \`thong_bao_id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_ZALO_OA_TOKENS_EXPIRES_AT\` ON \`zalo_oa_tokens\` (\`expires_at\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_ZALO_OA_TOKENS_ACTIVE\` ON \`zalo_oa_tokens\` (\`is_active\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_ZALO_OA_TOKENS_OA_ID\` ON \`zalo_oa_tokens\` (\`oa_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_b613a83f8b87de0702c28d313a\` ON \`zalo_users\` (\`userId\`)`);
        await queryRunner.query(`ALTER TABLE \`bao_cao_doan_so_theo_ky\` ADD CONSTRAINT \`FK_a9965c72442628611a11248f7b7\` FOREIGN KEY (\`nguoiPheDuyetId\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`su_kien\` ADD CONSTRAINT \`FK_630e9783fba0b045f06c98ae40c\` FOREIGN KEY (\`nguoi_tao\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`su_kien\` ADD CONSTRAINT \`FK_df41da1d74c009fa12e7ed539b5\` FOREIGN KEY (\`loai_su_kien_id\`) REFERENCES \`loai_su_kien\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`nguoi_nhan_su_kien\` ADD CONSTRAINT \`FK_c8ca505fdb3cbeee5b8e6e74fd4\` FOREIGN KEY (\`nguoi_nhan_id\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`nguoi_nhan_su_kien\` ADD CONSTRAINT \`FK_c9c0c784047d6ef1e6e6eab1c39\` FOREIGN KEY (\`su_kien_id\`) REFERENCES \`su_kien\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`organization\` ADD CONSTRAINT \`FK_079dcb6c2dcba57964876efa1d3\` FOREIGN KEY (\`cumKhuCnId\`) REFERENCES \`cum_khu_cong_nghiep\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`organization\` ADD CONSTRAINT \`FK_5b8a3ff5fa90193e3cac9cbe97a\` FOREIGN KEY (\`xaPhuongId\`) REFERENCES \`xa_phuong\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_thong_bao\` ADD CONSTRAINT \`FK_eb3893de9a67dee7a9ab35e06b8\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_thong_bao\` ADD CONSTRAINT \`FK_121005925439955f04182b52cc4\` FOREIGN KEY (\`thong_bao_id\`) REFERENCES \`thong_bao\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`thong_bao\` ADD CONSTRAINT \`FK_a0f7bab7d0bd6918820e0430545\` FOREIGN KEY (\`nguoi_gui\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`zalo_sessions\` ADD CONSTRAINT \`FK_e99bbb4d8e52caf8776f5f50fd1\` FOREIGN KEY (\`zalo_account_id\`) REFERENCES \`zalo_accounts\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`zalo_accounts\` ADD CONSTRAINT \`FK_453d0645ccd402152bf911c2f41\` FOREIGN KEY (\`user_id\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`zalo_users\` ADD CONSTRAINT \`FK_b613a83f8b87de0702c28d313a3\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`zalo_users\` DROP FOREIGN KEY \`FK_b613a83f8b87de0702c28d313a3\``);
        await queryRunner.query(`ALTER TABLE \`zalo_accounts\` DROP FOREIGN KEY \`FK_453d0645ccd402152bf911c2f41\``);
        await queryRunner.query(`ALTER TABLE \`zalo_sessions\` DROP FOREIGN KEY \`FK_e99bbb4d8e52caf8776f5f50fd1\``);
        await queryRunner.query(`ALTER TABLE \`thong_bao\` DROP FOREIGN KEY \`FK_a0f7bab7d0bd6918820e0430545\``);
        await queryRunner.query(`ALTER TABLE \`user_thong_bao\` DROP FOREIGN KEY \`FK_121005925439955f04182b52cc4\``);
        await queryRunner.query(`ALTER TABLE \`user_thong_bao\` DROP FOREIGN KEY \`FK_eb3893de9a67dee7a9ab35e06b8\``);
        await queryRunner.query(`ALTER TABLE \`organization\` DROP FOREIGN KEY \`FK_5b8a3ff5fa90193e3cac9cbe97a\``);
        await queryRunner.query(`ALTER TABLE \`organization\` DROP FOREIGN KEY \`FK_079dcb6c2dcba57964876efa1d3\``);
        await queryRunner.query(`ALTER TABLE \`nguoi_nhan_su_kien\` DROP FOREIGN KEY \`FK_c9c0c784047d6ef1e6e6eab1c39\``);
        await queryRunner.query(`ALTER TABLE \`nguoi_nhan_su_kien\` DROP FOREIGN KEY \`FK_c8ca505fdb3cbeee5b8e6e74fd4\``);
        await queryRunner.query(`ALTER TABLE \`su_kien\` DROP FOREIGN KEY \`FK_df41da1d74c009fa12e7ed539b5\``);
        await queryRunner.query(`ALTER TABLE \`su_kien\` DROP FOREIGN KEY \`FK_630e9783fba0b045f06c98ae40c\``);
        await queryRunner.query(`ALTER TABLE \`bao_cao_doan_so_theo_ky\` DROP FOREIGN KEY \`FK_a9965c72442628611a11248f7b7\``);
        await queryRunner.query(`DROP INDEX \`REL_b613a83f8b87de0702c28d313a\` ON \`zalo_users\``);
        await queryRunner.query(`DROP INDEX \`IDX_ZALO_OA_TOKENS_OA_ID\` ON \`zalo_oa_tokens\``);
        await queryRunner.query(`DROP INDEX \`IDX_ZALO_OA_TOKENS_ACTIVE\` ON \`zalo_oa_tokens\``);
        await queryRunner.query(`DROP INDEX \`IDX_ZALO_OA_TOKENS_EXPIRES_AT\` ON \`zalo_oa_tokens\``);
        await queryRunner.query(`DROP INDEX \`UK_user_thong_bao\` ON \`user_thong_bao\``);
        await queryRunner.query(`DROP INDEX \`IDX_9b05ed01c36388ac6f45dee0a0\` ON \`OrganizationFieldSchema\``);
        await queryRunner.query(`ALTER TABLE \`zalo_users\` CHANGE \`isActive\` \`isActive\` tinyint(1) NOT NULL COMMENT 'Trạng thái hoạt động' DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`zalo_users\` CHANGE \`avatar\` \`avatar\` text COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`zalo_users\` CHANGE \`name\` \`name\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`zalo_users\` DROP INDEX \`IDX_fa9be7c269ee7b665ca0c13a1c\``);
        await queryRunner.query(`ALTER TABLE \`zalo_users\` CHANGE \`zaloId\` \`zaloId\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`zalo_oa_tokens\` CHANGE \`updated_at\` \`updated_at\` datetime(0) NULL COMMENT 'Thời gian cập nhật' DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`zalo_oa_tokens\` CHANGE \`created_at\` \`created_at\` datetime(0) NULL COMMENT 'Thời gian tạo' DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`zalo_oa_tokens\` CHANGE \`is_active\` \`is_active\` tinyint NULL COMMENT '1: Active, 0: Inactive' DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`zalo_oa_tokens\` CHANGE \`token_type\` \`token_type\` varchar(50) NULL COMMENT 'Loại token' DEFAULT 'Bearer'`);
        await queryRunner.query(`ALTER TABLE \`zalo_oa_tokens\` CHANGE \`expires_at\` \`expires_at\` datetime NULL COMMENT 'Thời điểm hết hạn token'`);
        await queryRunner.query(`ALTER TABLE \`zalo_oa_tokens\` CHANGE \`expires_in\` \`expires_in\` int NULL COMMENT 'Thời gian hết hạn token (seconds)'`);
        await queryRunner.query(`ALTER TABLE \`zalo_oa_tokens\` CHANGE \`access_token\` \`access_token\` text NULL COMMENT 'Access token của Zalo OA'`);
        await queryRunner.query(`ALTER TABLE \`zalo_oa_tokens\` CHANGE \`oa_id\` \`oa_id\` varchar(255) NULL COMMENT 'Zalo OA ID'`);
        await queryRunner.query(`ALTER TABLE \`zalo_accounts\` CHANGE \`updated_at\` \`updated_at\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`zalo_accounts\` CHANGE \`created_at\` \`created_at\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`zalo_accounts\` CHANGE \`is_active\` \`is_active\` tinyint(1) NOT NULL COMMENT 'Active status' DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`zalo_accounts\` CHANGE \`last_login_at\` \`last_login_at\` datetime NULL COMMENT 'Last login time'`);
        await queryRunner.query(`ALTER TABLE \`zalo_accounts\` CHANGE \`additional_info\` \`additional_info\` json NULL COMMENT 'Extra info from Zalo'`);
        await queryRunner.query(`ALTER TABLE \`zalo_accounts\` CHANGE \`last_active_at\` \`last_active_at\` datetime NULL COMMENT 'Lần tương tác gần nhất'`);
        await queryRunner.query(`ALTER TABLE \`zalo_accounts\` CHANGE \`last_unfollow_at\` \`last_unfollow_at\` datetime NULL COMMENT 'Lần unfollow OA gần nhất'`);
        await queryRunner.query(`ALTER TABLE \`zalo_accounts\` CHANGE \`last_follow_at\` \`last_follow_at\` datetime NULL COMMENT 'Lần follow OA gần nhất'`);
        await queryRunner.query(`ALTER TABLE \`zalo_accounts\` CHANGE \`is_following_oa\` \`is_following_oa\` tinyint NOT NULL COMMENT 'Có đang follow OA không' DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`zalo_sessions\` CHANGE \`updated_at\` \`updated_at\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`zalo_sessions\` CHANGE \`created_at\` \`created_at\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`zalo_sessions\` CHANGE \`expires_at\` \`expires_at\` datetime NULL COMMENT 'Thời điểm token hết hạn'`);
        await queryRunner.query(`ALTER TABLE \`UserToken\` CHANGE \`isActive\` \`isActive\` int NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`role\` CHANGE \`isActive\` \`isActive\` int NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`organization\` CHANGE \`updatedAt\` \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`organization\` CHANGE \`createdAt\` \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`organization\` CHANGE \`slCongDoanNu\` \`slCongDoanNu\` int NULL COMMENT 'Số lượng công đoàn nữ' DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`organization\` CHANGE \`slCongDoanNam\` \`slCongDoanNam\` int NULL COMMENT 'Số lượng công đoàn nam' DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`organization\` CHANGE \`slCongNhanVienChucLdNu\` \`slCongNhanVienChucLdNu\` int NULL COMMENT 'Số lượng công nhân viên chức lao động nữ' DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`organization\` CHANGE \`slCongNhanVienChucLdNam\` \`slCongNhanVienChucLdNam\` int NULL COMMENT 'Số lượng công nhân viên chức lao động nam' DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`organization\` CHANGE \`name\` \`name\` varchar(255) COLLATE "utf8mb4_unicode_ci" NOT NULL COMMENT 'Tên tổ chức' DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE \`nguoi_nhan_su_kien\` CHANGE \`updated_at\` \`updated_at\` datetime(6) NOT NULL COMMENT 'Ngày cập nhật' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`nguoi_nhan_su_kien\` CHANGE \`created_at\` \`created_at\` datetime(6) NOT NULL COMMENT 'Ngày tạo' DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`nguoi_nhan_su_kien\` CHANGE \`ghi_chu\` \`ghi_chu\` text COLLATE "utf8mb4_unicode_ci" NULL COMMENT 'Ghi chú thêm'`);
        await queryRunner.query(`ALTER TABLE \`nguoi_nhan_su_kien\` CHANGE \`loai_thong_bao\` \`loai_thong_bao\` varchar(50) CHARACTER SET "utf8mb3" COLLATE "utf8mb3_general_ci" NOT NULL COMMENT 'Loại thông báo' DEFAULT 'Thông báo sự kiện'`);
        await queryRunner.query(`ALTER TABLE \`nguoi_nhan_su_kien\` CHANGE \`thoi_gian_xem\` \`thoi_gian_xem\` datetime NULL COMMENT 'Thời gian người dùng xem thông báo'`);
        await queryRunner.query(`ALTER TABLE \`nguoi_nhan_su_kien\` CHANGE \`thoi_gian_gui\` \`thoi_gian_gui\` datetime NOT NULL COMMENT 'Thời gian gửi thông báo' DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`nguoi_nhan_su_kien\` CHANGE \`trang_thai_xem\` \`trang_thai_xem\` varchar(20) CHARACTER SET "utf8mb3" COLLATE "utf8mb3_general_ci" NOT NULL COMMENT 'Trạng thái xem: Đã xem, Chưa xem' DEFAULT 'Chưa xem'`);
        await queryRunner.query(`ALTER TABLE \`nguoi_nhan_su_kien\` CHANGE \`su_kien_id\` \`su_kien_id\` int NOT NULL COMMENT 'ID sự kiện'`);
        await queryRunner.query(`ALTER TABLE \`su_kien\` CHANGE \`updated_at\` \`updated_at\` datetime(6) NOT NULL COMMENT 'Ngày cập nhật' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`su_kien\` CHANGE \`created_at\` \`created_at\` datetime(6) NOT NULL COMMENT 'Ngày tạo' DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`su_kien\` CHANGE \`ghi_chu\` \`ghi_chu\` text COLLATE "utf8mb4_unicode_ci" NULL COMMENT 'Ghi chú thêm'`);
        await queryRunner.query(`ALTER TABLE \`su_kien\` CHANGE \`file_dinh_kem\` \`file_dinh_kem\` text COLLATE "utf8mb4_unicode_ci" NULL COMMENT 'Đường dẫn file đính kèm (JSON format)'`);
        await queryRunner.query(`ALTER TABLE \`su_kien\` CHANGE \`so_luong_tham_gia_du_kien\` \`so_luong_tham_gia_du_kien\` int NULL COMMENT 'Số lượng dự kiến tham gia' DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`su_kien\` CHANGE \`loai_su_kien_id\` \`loai_su_kien_id\` int NULL COMMENT 'ID loại sự kiện'`);
        await queryRunner.query(`ALTER TABLE \`su_kien\` CHANGE \`doi_tuong\` \`doi_tuong\` varchar(255) CHARACTER SET "utf8mb3" COLLATE "utf8mb3_general_ci" NULL COMMENT 'Đối tượng tham gia'`);
        await queryRunner.query(`ALTER TABLE \`su_kien\` CHANGE \`trang_thai\` \`trang_thai\` varchar(50) CHARACTER SET "utf8mb3" COLLATE "utf8mb3_general_ci" NOT NULL COMMENT 'Trạng thái sự kiện' DEFAULT 'Đang chuẩn bị'`);
        await queryRunner.query(`ALTER TABLE \`su_kien\` CHANGE \`dia_diem\` \`dia_diem\` varchar(255) CHARACTER SET "utf8mb3" COLLATE "utf8mb3_general_ci" NULL COMMENT 'Địa điểm tổ chức'`);
        await queryRunner.query(`ALTER TABLE \`su_kien\` CHANGE \`noi_dung_su_kien\` \`noi_dung_su_kien\` text COLLATE "utf8mb4_unicode_ci" NULL COMMENT 'Nội dung chi tiết sự kiện'`);
        await queryRunner.query(`ALTER TABLE \`su_kien\` CHANGE \`thoi_gian_ket_thuc\` \`thoi_gian_ket_thuc\` datetime NOT NULL COMMENT 'Thời gian kết thúc'`);
        await queryRunner.query(`ALTER TABLE \`su_kien\` CHANGE \`thoi_gian_bat_dau\` \`thoi_gian_bat_dau\` datetime NOT NULL COMMENT 'Thời gian bắt đầu'`);
        await queryRunner.query(`ALTER TABLE \`su_kien\` CHANGE \`ten_su_kien\` \`ten_su_kien\` varchar(255) CHARACTER SET "utf8mb3" COLLATE "utf8mb3_general_ci" NOT NULL COMMENT 'Tên sự kiện'`);
        await queryRunner.query(`ALTER TABLE \`loai_su_kien\` CHANGE \`updated_at\` \`updated_at\` datetime(6) NOT NULL COMMENT 'Ngày cập nhật' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`loai_su_kien\` CHANGE \`created_at\` \`created_at\` datetime(6) NOT NULL COMMENT 'Ngày tạo' DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`loai_su_kien\` CHANGE \`trang_thai\` \`trang_thai\` tinyint(1) NOT NULL COMMENT 'Trạng thái hoạt động' DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`loai_su_kien\` CHANGE \`mo_ta\` \`mo_ta\` varchar(500) CHARACTER SET "utf8mb3" COLLATE "utf8mb3_general_ci" NULL COMMENT 'Mô tả loại sự kiện'`);
        await queryRunner.query(`ALTER TABLE \`loai_su_kien\` CHANGE \`ten\` \`ten\` varchar(255) CHARACTER SET "utf8mb3" COLLATE "utf8mb3_general_ci" NOT NULL COMMENT 'Tên loại sự kiện'`);
        await queryRunner.query(`ALTER TABLE \`oa_follow_events\` CHANGE \`created_at\` \`created_at\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`oa_follow_events\` CHANGE \`zalo_oa_user_id\` \`zalo_oa_user_id\` varchar(50) NOT NULL COMMENT 'ID của user từ webhook event'`);
        await queryRunner.query(`ALTER TABLE \`bao_cao_doan_so_theo_ky\` CHANGE \`ngayPheDuyet\` \`ngayPheDuyet\` datetime NULL COMMENT 'Ngày giờ phê duyệt hoặc từ chối báo cáo'`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`xaPhuongId\` \`xaPhuongId\` int NULL COMMENT 'ID của xã phường'`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`cumKhuCnId\` \`cumKhuCnId\` int NULL COMMENT 'ID của cụm khu công nghiệp'`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`email\` \`email\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`fullName\` \`fullName\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`forgetPassCode\` \`forgetPassCode\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`zalo_users\` CHANGE \`isActive\` \`isActive\` tinyint(1) NOT NULL COMMENT 'Trạng thái hoạt động' DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`zalo_users\` DROP INDEX \`IDX_b613a83f8b87de0702c28d313a\``);
        await queryRunner.query(`ALTER TABLE \`zalo_users\` DROP COLUMN \`userId\``);
        await queryRunner.query(`ALTER TABLE \`zalo_users\` ADD \`userId\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`zalo_users\` CHANGE \`avatar\` \`avatar\` text COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`zalo_users\` DROP COLUMN \`phone\``);
        await queryRunner.query(`ALTER TABLE \`zalo_users\` ADD \`phone\` varchar(20) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`zalo_users\` CHANGE \`name\` \`name\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`zalo_users\` DROP INDEX \`IDX_fa9be7c269ee7b665ca0c13a1c\``);
        await queryRunner.query(`ALTER TABLE \`zalo_users\` CHANGE \`zaloId\` \`zaloId\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`zalo_accounts\` CHANGE \`updated_at\` \`updated_at\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`zalo_accounts\` CHANGE \`created_at\` \`created_at\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`zalo_accounts\` CHANGE \`is_active\` \`is_active\` tinyint(1) NOT NULL COMMENT 'Active status' DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`zalo_accounts\` CHANGE \`last_login_at\` \`last_login_at\` datetime NULL COMMENT 'Last login time'`);
        await queryRunner.query(`ALTER TABLE \`zalo_accounts\` CHANGE \`additional_info\` \`additional_info\` json NULL COMMENT 'Extra info from Zalo'`);
        await queryRunner.query(`ALTER TABLE \`zalo_accounts\` DROP COLUMN \`phone\``);
        await queryRunner.query(`ALTER TABLE \`zalo_accounts\` ADD \`phone\` varchar(20) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`zalo_accounts\` CHANGE \`last_active_at\` \`last_active_at\` datetime NULL COMMENT 'Lần tương tác gần nhất'`);
        await queryRunner.query(`ALTER TABLE \`zalo_accounts\` CHANGE \`last_unfollow_at\` \`last_unfollow_at\` datetime NULL COMMENT 'Lần unfollow OA gần nhất'`);
        await queryRunner.query(`ALTER TABLE \`zalo_accounts\` CHANGE \`last_follow_at\` \`last_follow_at\` datetime NULL COMMENT 'Lần follow OA gần nhất'`);
        await queryRunner.query(`ALTER TABLE \`zalo_accounts\` CHANGE \`is_following_oa\` \`is_following_oa\` tinyint NOT NULL COMMENT 'Có đang follow OA không' DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`zalo_accounts\` DROP COLUMN \`avatar\``);
        await queryRunner.query(`ALTER TABLE \`zalo_accounts\` ADD \`avatar\` text COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`zalo_accounts\` DROP COLUMN \`user_id\``);
        await queryRunner.query(`ALTER TABLE \`zalo_accounts\` ADD \`user_id\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`zalo_accounts\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`zalo_accounts\` ADD \`id\` bigint NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`zalo_accounts\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`zalo_accounts\` CHANGE \`id\` \`id\` bigint NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`zalo_sessions\` CHANGE \`updated_at\` \`updated_at\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`zalo_sessions\` CHANGE \`created_at\` \`created_at\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`zalo_sessions\` CHANGE \`expires_at\` \`expires_at\` datetime NULL COMMENT 'Thời điểm token hết hạn'`);
        await queryRunner.query(`ALTER TABLE \`zalo_sessions\` DROP COLUMN \`refresh_token\``);
        await queryRunner.query(`ALTER TABLE \`zalo_sessions\` ADD \`refresh_token\` text NULL COMMENT 'Refresh token từ Zalo'`);
        await queryRunner.query(`ALTER TABLE \`zalo_sessions\` DROP COLUMN \`access_token\``);
        await queryRunner.query(`ALTER TABLE \`zalo_sessions\` ADD \`access_token\` text NULL COMMENT 'Access token từ Zalo'`);
        await queryRunner.query(`ALTER TABLE \`zalo_sessions\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`zalo_sessions\` ADD \`id\` bigint NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`zalo_sessions\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`zalo_sessions\` CHANGE \`id\` \`id\` bigint NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`zalo_oa_tokens\` CHANGE \`updated_at\` \`updated_at\` datetime(0) NULL COMMENT 'Thời gian cập nhật' DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`zalo_oa_tokens\` CHANGE \`created_at\` \`created_at\` datetime(0) NULL COMMENT 'Thời gian tạo' DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`zalo_oa_tokens\` CHANGE \`is_active\` \`is_active\` tinyint NULL COMMENT '1: Active, 0: Inactive' DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`zalo_oa_tokens\` CHANGE \`token_type\` \`token_type\` varchar(50) NULL COMMENT 'Loại token' DEFAULT 'Bearer'`);
        await queryRunner.query(`ALTER TABLE \`zalo_oa_tokens\` CHANGE \`expires_at\` \`expires_at\` datetime NULL COMMENT 'Thời điểm hết hạn token'`);
        await queryRunner.query(`ALTER TABLE \`zalo_oa_tokens\` CHANGE \`expires_in\` \`expires_in\` int NULL COMMENT 'Thời gian hết hạn token (seconds)'`);
        await queryRunner.query(`ALTER TABLE \`zalo_oa_tokens\` CHANGE \`access_token\` \`access_token\` text NULL COMMENT 'Access token của Zalo OA'`);
        await queryRunner.query(`ALTER TABLE \`zalo_oa_tokens\` CHANGE \`oa_id\` \`oa_id\` varchar(255) NULL COMMENT 'Zalo OA ID'`);
        await queryRunner.query(`ALTER TABLE \`UserToken\` CHANGE \`isActive\` \`isActive\` int NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`UserToken\` DROP COLUMN \`deviceInfo\``);
        await queryRunner.query(`ALTER TABLE \`UserToken\` ADD \`deviceInfo\` varchar(500) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`UserToken\` DROP COLUMN \`token\``);
        await queryRunner.query(`ALTER TABLE \`UserToken\` ADD \`token\` varchar(1000) COLLATE "utf8mb4_unicode_ci" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`thong_bao\` DROP COLUMN \`nguoi_gui\``);
        await queryRunner.query(`ALTER TABLE \`thong_bao\` ADD \`nguoi_gui\` varchar(255) COLLATE "utf8mb4_unicode_ci" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`user_thong_bao\` DROP COLUMN \`trang_thai\``);
        await queryRunner.query(`ALTER TABLE \`user_thong_bao\` ADD \`trang_thai\` varchar(255) COLLATE "utf8mb4_unicode_ci" NOT NULL DEFAULT 'chua_doc'`);
        await queryRunner.query(`ALTER TABLE \`user_thong_bao\` DROP COLUMN \`userId\``);
        await queryRunner.query(`ALTER TABLE \`user_thong_bao\` ADD \`userId\` varchar(255) COLLATE "utf8mb4_unicode_ci" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`role\` DROP COLUMN \`description\``);
        await queryRunner.query(`ALTER TABLE \`role\` ADD \`description\` varchar(500) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`role\` DROP COLUMN \`permissions\``);
        await queryRunner.query(`ALTER TABLE \`role\` ADD \`permissions\` text COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`role\` CHANGE \`isActive\` \`isActive\` int NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`organization\` CHANGE \`updatedAt\` \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`organization\` CHANGE \`createdAt\` \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`organization\` CHANGE \`slCongDoanNu\` \`slCongDoanNu\` int NULL COMMENT 'Số lượng công đoàn nữ' DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`organization\` CHANGE \`slCongDoanNam\` \`slCongDoanNam\` int NULL COMMENT 'Số lượng công đoàn nam' DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`organization\` CHANGE \`slCongNhanVienChucLdNu\` \`slCongNhanVienChucLdNu\` int NULL COMMENT 'Số lượng công nhân viên chức lao động nữ' DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`organization\` CHANGE \`slCongNhanVienChucLdNam\` \`slCongNhanVienChucLdNam\` int NULL COMMENT 'Số lượng công nhân viên chức lao động nam' DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`organization\` CHANGE \`name\` \`name\` varchar(255) COLLATE "utf8mb4_unicode_ci" NOT NULL COMMENT 'Tên tổ chức' DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE \`nguoi_nhan_su_kien\` CHANGE \`updated_at\` \`updated_at\` datetime(6) NOT NULL COMMENT 'Ngày cập nhật' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`nguoi_nhan_su_kien\` CHANGE \`created_at\` \`created_at\` datetime(6) NOT NULL COMMENT 'Ngày tạo' DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`nguoi_nhan_su_kien\` CHANGE \`ghi_chu\` \`ghi_chu\` text COLLATE "utf8mb4_unicode_ci" NULL COMMENT 'Ghi chú thêm'`);
        await queryRunner.query(`ALTER TABLE \`nguoi_nhan_su_kien\` CHANGE \`loai_thong_bao\` \`loai_thong_bao\` varchar(50) CHARACTER SET "utf8mb3" COLLATE "utf8mb3_general_ci" NOT NULL COMMENT 'Loại thông báo' DEFAULT 'Thông báo sự kiện'`);
        await queryRunner.query(`ALTER TABLE \`nguoi_nhan_su_kien\` CHANGE \`thoi_gian_xem\` \`thoi_gian_xem\` datetime NULL COMMENT 'Thời gian người dùng xem thông báo'`);
        await queryRunner.query(`ALTER TABLE \`nguoi_nhan_su_kien\` CHANGE \`thoi_gian_gui\` \`thoi_gian_gui\` datetime NOT NULL COMMENT 'Thời gian gửi thông báo' DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`nguoi_nhan_su_kien\` CHANGE \`trang_thai_xem\` \`trang_thai_xem\` varchar(20) CHARACTER SET "utf8mb3" COLLATE "utf8mb3_general_ci" NOT NULL COMMENT 'Trạng thái xem: Đã xem, Chưa xem' DEFAULT 'Chưa xem'`);
        await queryRunner.query(`ALTER TABLE \`nguoi_nhan_su_kien\` CHANGE \`su_kien_id\` \`su_kien_id\` int NOT NULL COMMENT 'ID sự kiện'`);
        await queryRunner.query(`ALTER TABLE \`nguoi_nhan_su_kien\` DROP COLUMN \`nguoi_nhan_id\``);
        await queryRunner.query(`ALTER TABLE \`nguoi_nhan_su_kien\` ADD \`nguoi_nhan_id\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL COMMENT 'ID người nhận thông báo'`);
        await queryRunner.query(`ALTER TABLE \`su_kien\` CHANGE \`updated_at\` \`updated_at\` datetime(6) NOT NULL COMMENT 'Ngày cập nhật' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`su_kien\` CHANGE \`created_at\` \`created_at\` datetime(6) NOT NULL COMMENT 'Ngày tạo' DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`su_kien\` CHANGE \`ghi_chu\` \`ghi_chu\` text COLLATE "utf8mb4_unicode_ci" NULL COMMENT 'Ghi chú thêm'`);
        await queryRunner.query(`ALTER TABLE \`su_kien\` CHANGE \`file_dinh_kem\` \`file_dinh_kem\` text COLLATE "utf8mb4_unicode_ci" NULL COMMENT 'Đường dẫn file đính kèm (JSON format)'`);
        await queryRunner.query(`ALTER TABLE \`su_kien\` CHANGE \`so_luong_tham_gia_du_kien\` \`so_luong_tham_gia_du_kien\` int NULL COMMENT 'Số lượng dự kiến tham gia' DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`su_kien\` CHANGE \`loai_su_kien_id\` \`loai_su_kien_id\` int NULL COMMENT 'ID loại sự kiện'`);
        await queryRunner.query(`ALTER TABLE \`su_kien\` CHANGE \`doi_tuong\` \`doi_tuong\` varchar(255) CHARACTER SET "utf8mb3" COLLATE "utf8mb3_general_ci" NULL COMMENT 'Đối tượng tham gia'`);
        await queryRunner.query(`ALTER TABLE \`su_kien\` CHANGE \`trang_thai\` \`trang_thai\` varchar(50) CHARACTER SET "utf8mb3" COLLATE "utf8mb3_general_ci" NOT NULL COMMENT 'Trạng thái sự kiện' DEFAULT 'Đang chuẩn bị'`);
        await queryRunner.query(`ALTER TABLE \`su_kien\` CHANGE \`dia_diem\` \`dia_diem\` varchar(255) CHARACTER SET "utf8mb3" COLLATE "utf8mb3_general_ci" NULL COMMENT 'Địa điểm tổ chức'`);
        await queryRunner.query(`ALTER TABLE \`su_kien\` CHANGE \`noi_dung_su_kien\` \`noi_dung_su_kien\` text COLLATE "utf8mb4_unicode_ci" NULL COMMENT 'Nội dung chi tiết sự kiện'`);
        await queryRunner.query(`ALTER TABLE \`su_kien\` DROP COLUMN \`nguoi_tao\``);
        await queryRunner.query(`ALTER TABLE \`su_kien\` ADD \`nguoi_tao\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL COMMENT 'User ID người tạo sự kiện'`);
        await queryRunner.query(`ALTER TABLE \`su_kien\` CHANGE \`thoi_gian_ket_thuc\` \`thoi_gian_ket_thuc\` datetime NOT NULL COMMENT 'Thời gian kết thúc'`);
        await queryRunner.query(`ALTER TABLE \`su_kien\` CHANGE \`thoi_gian_bat_dau\` \`thoi_gian_bat_dau\` datetime NOT NULL COMMENT 'Thời gian bắt đầu'`);
        await queryRunner.query(`ALTER TABLE \`su_kien\` CHANGE \`ten_su_kien\` \`ten_su_kien\` varchar(255) CHARACTER SET "utf8mb3" COLLATE "utf8mb3_general_ci" NOT NULL COMMENT 'Tên sự kiện'`);
        await queryRunner.query(`ALTER TABLE \`oa_follow_events\` CHANGE \`created_at\` \`created_at\` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`oa_follow_events\` CHANGE \`zalo_oa_user_id\` \`zalo_oa_user_id\` varchar(50) NOT NULL COMMENT 'ID của user từ webhook event'`);
        await queryRunner.query(`ALTER TABLE \`oa_follow_events\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`oa_follow_events\` ADD \`id\` bigint NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`oa_follow_events\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`oa_follow_events\` CHANGE \`id\` \`id\` bigint NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`loai_su_kien\` CHANGE \`updated_at\` \`updated_at\` datetime(6) NOT NULL COMMENT 'Ngày cập nhật' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`loai_su_kien\` CHANGE \`created_at\` \`created_at\` datetime(6) NOT NULL COMMENT 'Ngày tạo' DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`loai_su_kien\` CHANGE \`trang_thai\` \`trang_thai\` tinyint(1) NOT NULL COMMENT 'Trạng thái hoạt động' DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`loai_su_kien\` CHANGE \`mo_ta\` \`mo_ta\` varchar(500) CHARACTER SET "utf8mb3" COLLATE "utf8mb3_general_ci" NULL COMMENT 'Mô tả loại sự kiện'`);
        await queryRunner.query(`ALTER TABLE \`loai_su_kien\` CHANGE \`ten\` \`ten\` varchar(255) CHARACTER SET "utf8mb3" COLLATE "utf8mb3_general_ci" NOT NULL COMMENT 'Tên loại sự kiện'`);
        await queryRunner.query(`ALTER TABLE \`bao_cao_doan_so_theo_ky\` CHANGE \`ngayPheDuyet\` \`ngayPheDuyet\` datetime NULL COMMENT 'Ngày giờ phê duyệt hoặc từ chối báo cáo'`);
        await queryRunner.query(`ALTER TABLE \`bao_cao_doan_so_theo_ky\` DROP COLUMN \`nguoiPheDuyetId\``);
        await queryRunner.query(`ALTER TABLE \`bao_cao_doan_so_theo_ky\` ADD \`nguoiPheDuyetId\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL COMMENT 'ID người phê duyệt hoặc từ chối báo cáo'`);
        await queryRunner.query(`ALTER TABLE \`bao_cao_doan_so_theo_ky\` DROP COLUMN \`trangThaiPheDuyet\``);
        await queryRunner.query(`ALTER TABLE \`bao_cao_doan_so_theo_ky\` ADD \`trangThaiPheDuyet\` varchar(255) COLLATE "utf8mb4_unicode_ci" NOT NULL DEFAULT 'cho_phe_duyet'`);
        await queryRunner.query(`ALTER TABLE \`bao_cao_doan_so_theo_ky\` CHANGE \`organizationId\` \`organizationId\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`xaPhuongId\` \`xaPhuongId\` int NULL COMMENT 'ID của xã phường'`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`cumKhuCnId\` \`cumKhuCnId\` int NULL COMMENT 'ID của cụm khu công nghiệp'`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`description\``);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`description\` varchar(500) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`avatar\``);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`avatar\` varchar(500) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`email\` \`email\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`phoneNumber\``);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`phoneNumber\` varchar(50) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`fullName\` \`fullName\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`forgetPassCode\` \`forgetPassCode\` varchar(255) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`id\` varchar(255) COLLATE "utf8mb4_unicode_ci" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`zalo_sessions\` DROP COLUMN \`is_active\``);
        await queryRunner.query(`ALTER TABLE \`zalo_sessions\` DROP COLUMN \`zalo_account_id\``);
        await queryRunner.query(`ALTER TABLE \`staff\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`staff\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`staff\` DROP COLUMN \`image\``);
        await queryRunner.query(`ALTER TABLE \`staff\` DROP COLUMN \`title\``);
        await queryRunner.query(`ALTER TABLE \`staff\` DROP COLUMN \`degree\``);
        await queryRunner.query(`ALTER TABLE \`oa_follow_events\` DROP COLUMN \`raw_data\``);
        await queryRunner.query(`ALTER TABLE \`oa_follow_events\` DROP COLUMN \`source\``);
        await queryRunner.query(`ALTER TABLE \`oa_follow_events\` DROP COLUMN \`timestamp\``);
        await queryRunner.query(`ALTER TABLE \`oa_follow_events\` DROP COLUMN \`event_name\``);
        await queryRunner.query(`ALTER TABLE \`bao_cao_doan_so_theo_ky\` DROP COLUMN \`cumKhuCnId\``);
        await queryRunner.query(`ALTER TABLE \`bao_cao_doan_so_theo_ky\` DROP COLUMN \`xaPhuongId\``);
        await queryRunner.query(`ALTER TABLE \`zalo_sessions\` ADD \`user_id\` varchar(255) NULL COMMENT 'Reference to user.id'`);
        await queryRunner.query(`ALTER TABLE \`zalo_sessions\` ADD \`status\` enum ('PENDING', 'AUTHORIZED', 'EXPIRED', 'REVOKED') NOT NULL COMMENT 'Trạng thái session' DEFAULT 'PENDING'`);
        await queryRunner.query(`ALTER TABLE \`zalo_sessions\` ADD \`session_key\` varchar(100) NOT NULL COMMENT 'Khóa session duy nhất (state từ OAuth)'`);
        await queryRunner.query(`ALTER TABLE \`zalo_sessions\` ADD \`redirect_uri\` varchar(500) NOT NULL COMMENT 'URI để redirect sau OAuth'`);
        await queryRunner.query(`ALTER TABLE \`zalo_sessions\` ADD \`oauth_code\` varchar(500) NULL COMMENT 'Authorization code từ Zalo'`);
        await queryRunner.query(`ALTER TABLE \`zalo_sessions\` ADD \`code_verifier\` varchar(128) NOT NULL COMMENT 'Code verifier cho PKCE'`);
        await queryRunner.query(`ALTER TABLE \`zalo_sessions\` ADD \`code_challenge\` varchar(128) NOT NULL COMMENT 'Code challenge cho PKCE'`);
        await queryRunner.query(`ALTER TABLE \`staff\` ADD \`workStartDate\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`staff\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`staff\` ADD \`taxCode\` varchar(20) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`staff\` ADD \`socialInsuranceNumber\` varchar(20) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`staff\` ADD \`salaryLevel\` decimal NULL`);
        await queryRunner.query(`ALTER TABLE \`staff\` ADD \`isDelete\` int NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`staff\` ADD \`isActive\` int NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`staff\` ADD \`healthInsuranceNumber\` varchar(20) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`staff\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`staff\` ADD \`contractType\` varchar(100) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`staff\` ADD \`bankName\` varchar(100) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`staff\` ADD \`bankAccount\` varchar(50) COLLATE "utf8mb4_unicode_ci" NULL`);
        await queryRunner.query(`ALTER TABLE \`organization\` ADD \`namThanhLap_backup\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`oa_follow_events\` ADD \`zalo_account_id\` bigint NULL COMMENT 'Liên kết với bảng zalo_accounts.id'`);
        await queryRunner.query(`ALTER TABLE \`oa_follow_events\` ADD \`updated_at\` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE \`oa_follow_events\` ADD \`processed_at\` datetime NULL COMMENT 'Thời điểm xử lý event'`);
        await queryRunner.query(`ALTER TABLE \`oa_follow_events\` ADD \`is_processed\` tinyint NOT NULL COMMENT 'Đã xử lý chưa' DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`oa_follow_events\` ADD \`event_type\` enum ('follow', 'unfollow') NOT NULL COMMENT 'Loại sự kiện'`);
        await queryRunner.query(`ALTER TABLE \`oa_follow_events\` ADD \`event_data\` json NULL COMMENT 'Dữ liệu gốc từ webhook'`);
        await queryRunner.query(`ALTER TABLE \`oa_follow_events\` ADD \`error_message\` text NULL COMMENT 'Lỗi nếu có khi xử lý'`);
        await queryRunner.query(`DROP TABLE \`zalo_tokens\``);
        await queryRunner.query(`DROP TABLE \`accounts\``);
        await queryRunner.query(`CREATE UNIQUE INDEX \`UK_zalo_users_zaloId\` ON \`zalo_users\` (\`zaloId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_zalo_accounts_zalo_mini_app_id\` ON \`zalo_accounts\` (\`zalo_mini_app_id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_zalo_accounts_user_id\` ON \`zalo_accounts\` (\`user_id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_zalo_accounts_oa_user_id\` ON \`zalo_accounts\` (\`zalo_oa_user_id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_zalo_accounts_following\` ON \`zalo_accounts\` (\`is_following_oa\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_zalo_accounts_app_user_id\` ON \`zalo_accounts\` (\`zalo_app_user_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`UQ_f6684d46d6ee3570e8dceef21c0\` ON \`zalo_sessions\` (\`session_key\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_zalo_sessions_user_id\` ON \`zalo_sessions\` (\`user_id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_zalo_sessions_status\` ON \`zalo_sessions\` (\`status\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_zalo_sessions_expires_at\` ON \`zalo_sessions\` (\`expires_at\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_oa_id\` ON \`zalo_oa_tokens\` (\`oa_id\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_expires_at\` ON \`zalo_oa_tokens\` (\`expires_at\`)`);
        await queryRunner.query(`CREATE INDEX \`idx_active\` ON \`zalo_oa_tokens\` (\`is_active\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_thoi_gian_cap_nhat_doan_so_time_range\` ON \`ThoiGianCapNhatDoanSo\` (\`thoiGianBatDau\`, \`thoiGianKetThuc\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_thoi_gian_cap_nhat_doan_so_next_notification\` ON \`ThoiGianCapNhatDoanSo\` (\`next_notification_time\`, \`auto_notification_enabled\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_thoi_gian_cap_nhat_doan_so_isActive\` ON \`ThoiGianCapNhatDoanSo\` (\`isActive\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_organization_field_schema_sort_active\` ON \`OrganizationFieldSchema\` (\`isActive\`, \`sortOrder\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_organization_field_schema_fieldKey\` ON \`OrganizationFieldSchema\` (\`fieldKey\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`fieldKey\` ON \`OrganizationFieldSchema\` (\`fieldKey\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_organization_cumKhuCnId\` ON \`organization\` (\`cumKhuCnId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`UK_nguoi_nhan_su_kien\` ON \`nguoi_nhan_su_kien\` (\`nguoi_nhan_id\`, \`su_kien_id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_oa_follow_events_zalo_account_id\` ON \`oa_follow_events\` (\`zalo_account_id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_oa_follow_events_type\` ON \`oa_follow_events\` (\`event_type\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_oa_follow_events_processed\` ON \`oa_follow_events\` (\`is_processed\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_oa_follow_events_oa_user_id\` ON \`oa_follow_events\` (\`zalo_oa_user_id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_bao_cao_doan_so_nguoi_phe_duyet\` ON \`bao_cao_doan_so_theo_ky\` (\`nguoiPheDuyetId\`)`);
        await queryRunner.query(`ALTER TABLE \`zalo_users\` ADD CONSTRAINT \`FK_zalo_users_userId\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`UserToken\` ADD CONSTRAINT \`FK_usertoken_user\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`thong_bao\` ADD CONSTRAINT \`FK_thong_bao_nguoi_gui\` FOREIGN KEY (\`nguoi_gui\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_thong_bao\` ADD CONSTRAINT \`FK_user_thong_bao_user\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_thong_bao\` ADD CONSTRAINT \`FK_user_thong_bao_thong_bao\` FOREIGN KEY (\`thong_bao_id\`) REFERENCES \`thong_bao\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`staff\` ADD CONSTRAINT \`FK_staff_organization\` FOREIGN KEY (\`organizationId\`) REFERENCES \`organization\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`organization\` ADD CONSTRAINT \`FK_organization_cumKhuCongNghiep\` FOREIGN KEY (\`cumKhuCnId\`) REFERENCES \`cum_khu_cong_nghiep\`(\`id\`) ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`nguoi_nhan_su_kien\` ADD CONSTRAINT \`FK_nguoi_nhan_su_kien_su_kien\` FOREIGN KEY (\`su_kien_id\`) REFERENCES \`su_kien\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`nguoi_nhan_su_kien\` ADD CONSTRAINT \`FK_nguoi_nhan_su_kien_nguoi_nhan\` FOREIGN KEY (\`nguoi_nhan_id\`) REFERENCES \`user\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`su_kien\` ADD CONSTRAINT \`FK_su_kien_nguoi_tao\` FOREIGN KEY (\`nguoi_tao\`) REFERENCES \`user\`(\`id\`) ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`su_kien\` ADD CONSTRAINT \`FK_su_kien_loai_su_kien\` FOREIGN KEY (\`loai_su_kien_id\`) REFERENCES \`loai_su_kien\`(\`id\`) ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`oa_follow_events\` ADD CONSTRAINT \`FK_bc8cf00c4644e654c84124b3fe2\` FOREIGN KEY (\`zalo_account_id\`) REFERENCES \`zalo_accounts\`(\`id\`) ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`user\` ADD CONSTRAINT \`FK_user_role\` FOREIGN KEY (\`roleId\`) REFERENCES \`role\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
